### ISSUE TITLE
CSS doesn't highlight all based frens

### ISSUE THREAD

**Issue by rndtrash** [rndtrash/rms-supporters-haters-highlighter#12]
E.g. I can't see "Based!" tag near of @tlani . Does it work for you?

**Comment by rndtrash** [comment]
I think selector might be too big for Chrome :D

**Comment by tekakutli** [comment]
yea I can see myself as based, you too, and I am using the CSS one with the rms-supporters.py turned off

**Comment by rndtrash** [comment]
Now it works for me, please check my changes
