### ISSUE TITLE
have to go out, check out this

### ISSUE THREAD

**Issue by tekakutli** [rndtrash/rms-supporters-haters-highlighter#14]
for the non-frens:

curl   -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/rms-open-letter/rms-open-letter.github.io/contributors | grep login  > test

try it too with: grep html_url

the documentation https://docs.github.com/en/rest/reference/repos#list-repository-contributors

see you in a week

**Comment by rndtrash** [comment]
Thanks, I'll check it out
See you soon! :)
