### ISSUE TITLE
Match GH links strictly

### ISSUE THREAD

**Issue by rndtrash** [rndtrash/rms-supporters-haters-highlighter#6]
Because sonetimes nicknames from both letters match partially and that causes misinformation :(

**Comment by tekakutli** [comment]
wait... maybe use mine then (the pull request)
want me to modify it so that its only through the yaml filenames?

**Comment by rndtrash** [comment]
> wait... maybe use mine then (the pull request)
> want me to modify it so that its only through the yaml filenames?

Yeah, I don't mind!
