### ISSUE TITLE
Make a release, please!

### ISSUE THREAD

**Issue by pekanius** [rndtrash/rms-supporters-haters-highlighter#9]
Make a release, for quick install, please.

**Comment by rndtrash** [comment]
> Make a release, for quick install, please.

Sure, but it might cause problems because of the GDPR law and how the data from both letters is collected without the direct consent.
On the other hand, if anyone complains I'll just remove CSS from releases tab, that's it :^)

**Comment by rndtrash** [comment]
https://github.com/rndtrash/rms-supporters-haters-highlighter/releases/tag/2.0.0
